// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AIOpsRes struct {
	Result string   `json:"result"`
	Detail []string `json:"detail"`
}

type ChatReq struct {
	Id       string `json:"id"`
	Question string `json:"question"`
}

type ChatRes struct {
	Answer string `json:"answer"`
}

type ChatStreamReq struct {
	Id       string `json:"id"`
	Question string `json:"question"`
}

type FileUploadRes struct {
	FileName string `json:"fileName"`
	FilePath string `json:"filePath"`
	FileSize int64  `json:"fileSize"`
}
