// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/quark1973/multiagent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ai_ops",
				Handler: AIOpsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: ChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat_stream",
				Handler: ChatStreamHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/feishu/event",
				Handler: FeishuEventHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: UploadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
